from pathlib import Path

periods_path = Path('fundamentals_periods.py')
text = periods_path.read_text()
old = '''                q3_ytd = cumulative_values.get(3)\n                q3_ytd_value = _finite((q3_ytd or {}).get("value"))\n                if annual_value is not None and q3_ytd_value is not None:\n                    value = annual_value - q3_ytd_value\n                    if math.isfinite(value):\n                        quarter_values[4] = _point(\n                            value=value,\n                            unit=unit,\n                            fiscal_year=period["fiscal_year"],\n                            fiscal_quarter=4,\n                            start=q3_end + timedelta(days=1),\n                            end=q4_end,\n                            calculation="derived_from_fy_less_9m",\n                            components=[annual, q3_ytd],\n                        )\n                elif annual_value is not None and all(q in quarter_values for q in (1, 2, 3)):\n                    value = annual_value - sum(float(quarter_values[q]["value"]) for q in (1, 2, 3))\n                    if math.isfinite(value):\n                        quarter_values[4] = _point(\n                            value=value,\n                            unit=unit,\n                            fiscal_year=period["fiscal_year"],\n                            fiscal_quarter=4,\n                            start=q3_end + timedelta(days=1),\n                            end=q4_end,\n                            calculation="derived_from_fy_less_q1_q2_q3",\n                            components=[annual] + [quarter_values[q] for q in (1, 2, 3)],\n                        )\n'''
new = '''                q3_ytd = cumulative_values.get(3)\n                q3_ytd_value = _finite((q3_ytd or {}).get("value"))\n                # Prefer the standard Q4 residual from the three standalone quarters.\n                # Later comparative filings can restate standalone quarters without\n                # reproducing the historical 9M cumulative fact on the same basis.\n                # Using FY - Q1 - Q2 - Q3 therefore preserves the accounting identity\n                # whenever all three quarters are available.\n                if annual_value is not None and all(q in quarter_values for q in (1, 2, 3)):\n                    value = annual_value - sum(float(quarter_values[q]["value"]) for q in (1, 2, 3))\n                    if math.isfinite(value):\n                        quarter_values[4] = _point(\n                            value=value,\n                            unit=unit,\n                            fiscal_year=period["fiscal_year"],\n                            fiscal_quarter=4,\n                            start=q3_end + timedelta(days=1),\n                            end=q4_end,\n                            calculation="derived_from_fy_less_q1_q2_q3",\n                            components=[annual] + [quarter_values[q] for q in (1, 2, 3)],\n                        )\n                elif annual_value is not None and q3_ytd_value is not None:\n                    value = annual_value - q3_ytd_value\n                    if math.isfinite(value):\n                        quarter_values[4] = _point(\n                            value=value,\n                            unit=unit,\n                            fiscal_year=period["fiscal_year"],\n                            fiscal_quarter=4,\n                            start=q3_end + timedelta(days=1),\n                            end=q4_end,\n                            calculation="derived_from_fy_less_9m",\n                            components=[annual, q3_ytd],\n                        )\n'''
if old not in text:
    if 'Prefer the standard Q4 residual' in text:
        print('Q4 reconciliation fix already present')
    else:
        raise SystemExit('Q4 block not found')
else:
    periods_path.write_text(text.replace(old, new, 1))

unit_path = Path('tests/test_fundamentals_periods.py')
unit = unit_path.read_text()
unit = unit.replace('self.assertEqual(revenue[-1]["calculation"], "derived_from_fy_less_9m")',
                    'self.assertEqual(revenue[-1]["calculation"], "derived_from_fy_less_q1_q2_q3")')
unit_path.write_text(unit)
